application:
  port: 8000
  host: 127.0.0.1
application_port: 8000
database:
  driver: "postgres"
  host: "127.0.0.1"
  port: 54321 # from docker. check init_db
  username: "postgres"
  password: "password"
  database_name: "newsletter"