#!/usr/bin/env bash

RANDOM_NUMBER=$(($RANDOM + $RANDOM % 112))

PAYLOAD="'name=Tom&email=hello.$RANDOM_NUMBER@email.com'"

echo $PAYLOAD;

curl -i -X POST -d $PAYLOAD http://localhost:8000/subscriptions
