#!/usr/bin/env bash

RANDOM_NUMBER=$(($RANDOM + $RANDOM % 112))

PAYLOAD="'name=Tom&email=hello.$RANDOM_NUMBER@email.com'"

curl -i -X POST -d 'name=Tom&email=hello.$RANDOM_NUMBER@email.com' http://localhost:8000/subscriptions
