application:
  port: 8000
  base_url: "http://127.0.0.1"
database:
  driver: "postgres"
  host: "localhost"
  port: 54321 # from docker. check init_db
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test_sender_email@gmail.com"
  authorization_token: "some-secret-token"
  timeout: 2000